services:
  api:
    container_name: emission-api
    environment:
      - ORIGIN=${ORIGIN:-localhost}
    build: emission-api/.
    ports:
      - 8000:8000
  frontend:
    container_name: emission-frontend
    build:
      context: emission-frontend/.
      args:
        ORIGIN: ${ORIGIN:-localhost}
    ports:
      - 3000:80