# Generated by Django 4.1.13 on 2025-03-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmissionFactors",
            fields=[
                (
                    "emission_factor_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("activity", models.CharField(max_length=120)),
                ("lookup_identifier", models.CharField(max_length=120)),
                ("unit", models.CharField(max_length=120)),
                ("co2e", models.FloatField()),
                ("scope", models.IntegerField()),
                ("category", models.IntegerField()),
            ],
        ),
    ]
