# Generated by Django 4.1.13 on 2025-03-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emission_calculator_backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AirTravel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("activity", models.CharField(max_length=50)),
                ("distance_travelled", models.BigIntegerField()),
                ("distance_unit", models.CharField(max_length=20)),
                ("flight_range", models.CharField(max_length=50)),
                ("passenger_class", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Electricty",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("activity", models.CharField(max_length=120)),
                ("date", models.DateField()),
                ("country", models.CharField(max_length=50)),
                ("electricity_useage", models.FloatField()),
                ("unit", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="PurchasedGoodsAndServices",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("activity", models.CharField(max_length=120)),
                ("supplier_category", models.CharField(max_length=120)),
                ("spend", models.BigIntegerField()),
                ("spend_unit", models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name="emissionfactors",
            old_name="emission_factor_id",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="emissionfactors",
            name="unit",
            field=models.CharField(max_length=20),
        ),
    ]
