# Generated by Django 5.1.7 on 2025-03-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "emission_calculator_backend",
            "0002_airtravel_electricty_purchasedgoodsandservices_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="emissionfactors",
            unique_together={("activity", "lookup_identifier", "unit")},
        ),
    ]
