# Generated by Django 5.1.7 on 2025-03-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emission_calculator_backend", "0003_alter_emissionfactors_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasedgoodsandservices",
            name="co2e",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
