# Generated by Django 5.1.7 on 2025-03-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emission_calculator_backend", "0004_purchasedgoodsandservices_co2e"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emissionfactors",
            name="category",
            field=models.IntegerField(null=True),
        ),
    ]
