# Generated by Django 5.1.7 on 2025-03-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "emission_calculator_backend",
            "0006_airtravel_category_airtravel_co2e_airtravel_scope_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="electricty",
            old_name="electricity_useage",
            new_name="electricity_usage",
        ),
    ]
