# Generated by Django 5.1.7 on 2025-03-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "emission_calculator_backend",
            "0007_rename_electricity_useage_electricty_electricity_usage",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="airtravel",
            name="booking_type",
            field=models.CharField(default="None", max_length=200),
            preserve_default=False,
        ),
    ]
