# Generated by Django 5.1.7 on 2025-03-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emission_calculator_backend", "0008_airtravel_booking_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Electricty",
            new_name="Electricity",
        ),
        migrations.AlterModelOptions(
            name="airtravel",
            options={"verbose_name_plural": "Air Travel"},
        ),
        migrations.AlterModelOptions(
            name="electricity",
            options={"verbose_name_plural": "Electricity"},
        ),
        migrations.AlterModelOptions(
            name="emissionfactors",
            options={"verbose_name_plural": "Emission Factors"},
        ),
        migrations.AlterModelOptions(
            name="purchasedgoodsandservices",
            options={"verbose_name_plural": "Purchased Goods and Services"},
        ),
    ]
